version: '2'
services:
  mongo:
    image: mongo:3.2.0

  storage:
    image: 1ambda/kafkalot-storage
    links:
      - mongo
    ports:
      - "3003"
    environment:
     - KAFKALOT_STORAGE_CONNECTOR_CLUSTERHOST=${KAFKALOT_STORAGE_CONNECTOR_CLUSTERHOST}
     - KAFKALOT_STORAGE_CONNECTOR_CLUSTERPORT=${KAFKALOT_STORAGE_CONNECTOR_CLUSTERPORT}
     - KAFKALOT_STORAGE_APP_PORT=3003
     - KAFKALOT_STORAGE_MONGO_HOST=mongo
     - KAFKALOT_STORAGE_MONGO_PORT=27017
     - KAFKALOT_STORAGE_MONGO_DB=kafkalot-local

  ui:
    image: 1ambda/kafkalot-ui
    links:
     - storage
    ports:
     - "80"
