package io.github.lambda.exception

object ErrorCode {
  val CONNECTOR_NOT_FOUND = "CONNECTOR_NOT_FOUND"
  val CONNECTOR_NAME_DUPLICATED = "CONNECTOR_NAME_DUPLICATED"
  val CANNOT_MODIFY_RUNNING_CONNECTOR_META =
    "CANNOT_MODIFY_RUNNING_CONNECTOR_META"
  val CANNOT_MODIFY_DISABLED_CONNECTOR_META =
    "CANNOT_MODIFY_DISABLED_CONNECTOR_META"
  val CANNOT_CREATE_RUNNING_CONNECTOR = "CANNOT_CREATE_RUNNING_CONNECTOR"
  val CANNOT_UPDATE_DUPLICATED_META = "CANNOT_UPDATE_DUPLICATED_META"
  val CANNOT_RUN_CONNECTOR_WHILE_DISABLING =
    "CANNOT_RUN_CONNECTOR_WHILE_DISABLING"
  val FAILED_TO_STOP_CONNECTOR = "FAILED_TO_STOP_CONNECTOR"
  val FAILED_TO_START_CONNECTOR = "FAILED_TO_START_CONNECTOR"
  val FAILED_TO_GET_CONNECTOR = "FAILED_TO_GET_CONNECTOR"
  val FAILED_TO_GET_CONNECTORS = "FAILED_TO_GET_CONNECTORS"
  val FAILED_TO_UPDATE_CONNECTOR_CONFIG = "FAILED_TO_UPDATE_CONNECTOR_CONFIG"
}
