package io.github.lambda.exception

object ErrorCode {
  val CONNECTOR_NAME_DUPLICATED = "CONNECTOR_NAME_DUPLICATED"
  val CANNOT_UPDATE_META_USING_PUT_API = "CANNOT_UPDATE_META_USING_PUT_API"
  val CANNOT_CREATE_RUNNING_CONNECTOR = "CANNOT_CREATE_RUNNING_CONNECTOR"
  val CANNOT_UPDATE_DUPLICATED_META = "CANNOT_UPDATE_DUPLICATED_META"
  val FAILED_TO_STOP_CONNECTOR = "FAILED_TO_STOP_CONNECTOR"
  val FAILED_TO_START_CONNECTOR = "FAILED_TO_START_CONNECTOR"
  val FAILED_TO_GET_CONNECTOR = "FAILED_TO_GET_CONNECTOR"
  val FAILED_TO_GET_CONNECTORS = "FAILED_TO_GET_CONNECTORS"
  val FAILED_TO_UPDATE_CONNECTOR_CONFIG = "FAILED_TO_UPDATE_CONNECTOR_CONFIG"
  val INVALID_CONNECTOR_COMMAND_OPERATION =
    "INVALID_CONNECTOR_COMMAND_OPERATION"
  val UNSUPPORTED_CONNECTOR_OPERATION = "UNSUPPORTED_CONNECTOR_OPERATION"
}
