export const Code = {
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  EMPTY_NAME: 'EMPTY_NAME',
  EMPTY_CONFIG: 'EMPTY_CONFIG',
  CANNOT_CHANGE_NAME: 'CANNOT_CHANGE_NAME',
  FOUND_DUPLICATED_CONNECTORS: 'FOUND_DUPLICATED_CONNECTORS',
  NO_SUCH_CONNECTOR: 'NO_SUCH_CONNECTOR',
  CANNOT_UPDATE_NON_REGISTERED_CONNECTOR: 'CANNOT_UPDATE_NON_REGISTERED_CONNECTOR',

  CANNOT_OPEN_REMOVE_DIALOG: 'CANNOT_OPEN_REMOVE_DIALOG',
  CONNECTOR_COMMAND_FAILED: 'CONNECTOR_COMMAND_FAILED',
  CANNOT_REMOVE_CONNECTOR: 'CANNOT_REMOVE_CONNECTOR',
  NO_SELECTED_CONNECTORS: 'NO_SELECTED_CONNECTORS',

  INVALID_TASKS: 'INVALID_TASKS',

  CANNOT_FETCH_ALL_CONNECTORS: 'CANNOT_FETCH_ALL_CONNECTORS',
  CANNOT_REMOVE_ALL_SELECTED_CONNECTORS: 'CANNOT_REMOVE_ALL_SELECTED_CONNECTORS',
  CANNOT_CONVERT_CONNECT_CONFIG_TYPE: 'CANNOT_CONVERT_CONNECT_CONFIG_TYPE',
  CANNOT_CONVERT_CONNECT_VALIDATION_RESULT: 'CANNOT_CONVERT_CONNECT_VALIDATION_RESULT',
  CANNOT_FIND_CONNECTOR_PLUGINS: 'CANNOT_FIND_CONNECTOR_PLUGINS',
  CONNECTOR_CONFIG_HAS_NO_CONNECTOR_CLASS_FIELD: 'CONNECTOR_CONFIG_HAS_NO_CONNECTOR_CLASS_FIELD',
}
