export const Code = {
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  EMPTY_NAME: 'EMPTY_NAME',
  EMPTY_CONFIG: 'EMPTY_CONFIG',
  CANNOT_CHANGE_NAME: 'CANNOT_CHANGE_NAME',
  FOUND_DUPLICATED_CONNECTORS: 'FOUND_DUPLICATED_CONNECTORS',
  NO_SUCH_CONNECTOR: 'NO_SUCH_CONNECTOR',
  CANNOT_UPDATE_NON_REGISTERED_CONNECTOR: 'CANNOT_UPDATE_NON_REGISTERED_CONNECTOR',

  CANNOT_OPEN_REMOVE_DIALOG: 'CANNOT_OPEN_REMOVE_DIALOG',
  CANNOT_REMOVE_CONNECTOR: 'CANNOT_REMOVE_CONNECTOR',
  CANNOT_DISABLE_CONNECTOR: 'CANNOT_DISABLE_CONNECTOR',
  CANNOT_ENABLE_CONNECTOR: 'CANNOT_ENABLE_CONNECTOR',
  CANNOT_START_CONNECTOR: 'CANNOT_START_CONNECTOR',
  CANNOT_STOP_CONNECTOR: 'CANNOT_STOP_CONNECTOR',
  NO_SELECTED_CONNECTORS: 'NO_SELECTED_CONNECTORS',
  
  CANNOT_START_ALL_SELECTED_CONNECTORS: 'CANNOT_START_ALL_SELECTED_CONNECTORS',
  CANNOT_STOP_ALL_SELECTED_CONNECTORS: 'CANNOT_STOP_ALL_SELECTED_CONNECTORS',
  CANNOT_REMOVE_ALL_SELECTED_CONNECTORS: 'CANNOT_REMOVE_ALL_SELECTED_CONNECTORS',
}
