export const Code = {
  INVALID_STATE: 'INVALID_STATE',
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  EMPTY_NAME: 'EMPTY_NAME',
  EMPTY_CONFIG: 'EMPTY_CONFIG',
  CANNOT_CHANGE_NAME: 'CANNOT_CHANGE_NAME',
  FOUND_DUPLICATED_CONNECTORS: 'FOUND_DUPLICATED_CONNECTORS',
  NO_SUCH_CONNECTOR: 'NO_SUCH_CONNECTOR',
  CANNOT_START_CONNECTOR: 'CANNOT_START_CONNECTOR',
  CANNOT_STOP_CONNECTOR: 'CANNOT_STOP_CONNECTOR',
  CANNOT_ENABLE_CONNECTOR: 'CANNOT_ENABLE_CONNECTOR',
  CANNOT_DISABLED_CONNECTOR: 'CANNOT_DISABLED_CONNECTOR',
}
