export const Code = {
  INVALID_STATE: 'INVALID_STATE',
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  EMPTY_NAME: 'EMPTY_NAME',
  CANNOT_CHANGE_NAME: 'CANNOT_CHANGE_NAME',
  FOUND_DUPLICATED_CONNECTORS: 'FOUND_DUPLICATED_CONNECTORS',
  NO_SUCH_CONNECTOR: 'NO_SUCH_CONNECTOR',
}
